/* Finally, some good music */
var app=new function()
{this.name="Righteous",
this.version="The Righteous team",
this.date="2024",
this.folder="asset-v1/",
this.looptime=11711,
this.bpm=164,
this.totalframe=570,
this.nbpolo=7,
this.nbloopbonus=2,
this.bonusloopA=!0,
this.bonusendloopA=!0,
this.recmaxloop=96,
this.recminloop=4,
this.recmintime=Math.round(this.looptime/1e3)*this.recminloop,
this.spritepolo="polo-sprite.png",
this.spritepolotshirt="polo-sprite-tshirt.png",
this.spritepicto="game-picto.png",
this.colBck="#44FFD3",
this.col0="#000000",
this.col1="#44FFD3",
this.col2="#44FFD3",
this.col3="#00CABF",
this.col4="#44FFD3",
this.animearray=
[{name:"01kick",color:"00CABF",uniqsnd:!0},
{name:"02snare",color:"00CABF",uniqsnd:!0},
{name:"03clic",color:"00CABF",uniqsnd:!0},
{name:"04klop",color:"00CABF",uniqsnd:!0},
{name:"05tombreak",color:"00CABF",uniqsnd:!0},
{name:"06bass",color:"00CABF",uniqsnd:!0},
{name:"07mmmhah",color:"00CABF",uniqsnd:!0},
{name:"08tututoung",color:"00CABF",uniqsnd:!0},
{name:"09boowop",color:"00CABF",uniqsnd:!0},
{name:"10woah",color:"00CABF",uniqsnd:!0},
{name:"11nugununugu",color:"00CABF",uniqsnd:!0},
{name:"12string",color:"00CABF",uniqsnd:!0},
{name:"13lowarp",color:"00CABF",uniqsnd:!0},
{name:"14settoarp",color:"00CABF",uniqsnd:!0},
{name:"15duuduuduu",color:"00CABF",uniqsnd:!0},
{name:"16somuch",color:"00CABF",uniqsnd:!1},
{name:"17casting",color:"00CABF",uniqsnd:!1},
{name:"18ahwoo",color:"00CABF",uniqsnd:!1},
{name:"19lastday",color:"00CABF",uniqsnd:!1},
{name:"20mind",color:"00CABF",uniqsnd:!1}
],this.bonusarray=[];for(var n=0,o=this.animearray.length;n<o;n++)
{var a=this.animearray[n].name;this.animearray[n].soundA=a+"_a",this.animearray[n].soundB=this.animearray[n].uniqsnd?a+"_a":a+"_b",this.animearray[n].anime=a+"-sprite.png",this.animearray[n].animeData=a+".json"}};